### ISSUE TITLE
Documents for Command Line Interface lost

### ISSUE THREAD

**Issue by xubeisi** [sylabs/singularity-userdocs#98]
## Which Document page:

https://sylabs.io/guides/3.0/user-guide/cli.html

### Expected results:

Command Line Interface

### Actual results:

https://github.com/sylabs/singularity-userdocs/blob/main/cli.rst seems empty

**Comment by dtrudg** [comment]
The documentation you are linking at https://sylabs.io/guides/3.0/user-guide/cli.html is for the very first 3.0 release, which has not been supported for some time. It's not currently possible to build the command line reference for 3.0 due to changes in Go, dependenecies, etc. The section is present for all newer version. E.g. for the current SingularityCE 3.10 see:

https://sylabs.io/guides/3.10/user-guide/cli.html

The file https://github.com/sylabs/singularity-userdocs/blob/main/cli.rst  does not include any content because the CLI documentation is generated at build time. It is not content that we write in this repository. When the documentation is compiled, that section is automatically generated from the SingularityCE source code.
